[package]
name = "freertos-cargo-build"
description = "Utility lib to help building FreeRTOS for rust projects"
version = "0.1.0"
authors = ["Tobias Kaupat <tk@lobaro.de>"]
edition = "2018"

[lib]

[dependencies]
cc = "1.0.52"
walkdir = "2.3.1"



